/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AllEntriesRouteImport } from './routes/all-entries'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as SettingsThemeRouteImport } from './routes/settings.theme'
import { Route as SettingsSyncRouteImport } from './routes/settings.sync'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as SettingsDataRouteImport } from './routes/settings.data'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AllEntriesRoute = AllEntriesRouteImport.update({
  id: '/all-entries',
  path: '/all-entries',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const SettingsThemeRoute = SettingsThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSyncRoute = SettingsSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDataRoute = SettingsDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => SettingsRoute,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/all-entries': typeof AllEntriesRoute
  '/docs': typeof DocsRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/docs/$slug': typeof DocsSlugRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/sync': typeof SettingsSyncRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/docs/': typeof DocsIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/all-entries': typeof AllEntriesRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/sync': typeof SettingsSyncRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/docs': typeof DocsIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/all-entries': typeof AllEntriesRoute
  '/docs': typeof DocsRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/docs/$slug': typeof DocsSlugRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/sync': typeof SettingsSyncRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/docs/': typeof DocsIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/all-entries'
    | '/docs'
    | '/settings'
    | '/docs/$slug'
    | '/settings/data'
    | '/settings/profile'
    | '/settings/sync'
    | '/settings/theme'
    | '/docs/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/all-entries'
    | '/docs/$slug'
    | '/settings/data'
    | '/settings/profile'
    | '/settings/sync'
    | '/settings/theme'
    | '/docs'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/all-entries'
    | '/docs'
    | '/settings'
    | '/docs/$slug'
    | '/settings/data'
    | '/settings/profile'
    | '/settings/sync'
    | '/settings/theme'
    | '/docs/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllEntriesRoute: typeof AllEntriesRoute
  DocsRoute: typeof DocsRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-entries': {
      id: '/all-entries'
      path: '/all-entries'
      fullPath: '/all-entries'
      preLoaderRoute: typeof AllEntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/settings/theme': {
      id: '/settings/theme'
      path: '/theme'
      fullPath: '/settings/theme'
      preLoaderRoute: typeof SettingsThemeRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/sync': {
      id: '/settings/sync'
      path: '/sync'
      fullPath: '/settings/sync'
      preLoaderRoute: typeof SettingsSyncRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/data': {
      id: '/settings/data'
      path: '/data'
      fullPath: '/settings/data'
      preLoaderRoute: typeof SettingsDataRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsSlugRoute: typeof DocsSlugRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSlugRoute: DocsSlugRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface SettingsRouteChildren {
  SettingsDataRoute: typeof SettingsDataRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsSyncRoute: typeof SettingsSyncRoute
  SettingsThemeRoute: typeof SettingsThemeRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsDataRoute: SettingsDataRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsSyncRoute: SettingsSyncRoute,
  SettingsThemeRoute: SettingsThemeRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllEntriesRoute: AllEntriesRoute,
  DocsRoute: DocsRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
